apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hprr5solg-go-gitops
  description: This is GitOps manifest for hprr5solg-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=hprr5solg-go
    backstage.io/kubernetes-id: hprr5solg-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hprr5solg-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hprr5solg-go
